FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production

COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install --include=dev
COPY frontend/ .
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
