"""Add disputes and api_keys

Revision ID: c30b0989c720
Revises: a1b2c3d4e5f6
Create Date: 2026-07-31 09:46:25.409500
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c30b0989c720'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recon_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_exception_id'), 'disputes', ['exception_id'], unique=False)
    op.create_index(op.f('ix_disputes_run_id'), 'disputes', ['run_id'], unique=False)
    op.create_index(op.f('ix_disputes_tenant_id'), 'disputes', ['tenant_id'], unique=False)
    op.alter_column('reconciliations', 'left_source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reconciliations', 'right_source_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reconciliations', 'right_source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reconciliations', 'left_source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_disputes_tenant_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_run_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_exception_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
