"""Add source_files table and source_file_id to rows

Revision ID: d7789096c36b
Revises: e98f0e217d9d
Create Date: 2026-07-31 00:52:53.048625
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7789096c36b'
down_revision: Union[str, None] = 'e98f0e217d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_files_data_source_id'), 'source_files', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_source_files_tenant_id'), 'source_files', ['tenant_id'], unique=False)
    op.add_column('data_source_rows', sa.Column('source_file_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_data_source_rows_source_file_id'), 'data_source_rows', ['source_file_id'], unique=False)
    op.create_foreign_key(None, 'data_source_rows', 'source_files', ['source_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_source_rows', type_='foreignkey')
    op.drop_index(op.f('ix_data_source_rows_source_file_id'), table_name='data_source_rows')
    op.drop_column('data_source_rows', 'source_file_id')
    op.drop_index(op.f('ix_source_files_tenant_id'), table_name='source_files')
    op.drop_index(op.f('ix_source_files_data_source_id'), table_name='source_files')
    op.drop_table('source_files')
    # ### end Alembic commands ###
