"""Initial schema

Revision ID: e98f0e217d9d
Revises: 
Create Date: 2026-07-30 20:54:46.935427
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e98f0e217d9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default=sa.text("'free'"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('consolidations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('child_recon_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('consolidation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consolidations_tenant_id'), 'consolidations', ['tenant_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='file_upload | api_connector | database'),
    sa.Column('connector_type', sa.String(length=100), nullable=True),
    sa.Column('connector_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_tenant_id'), 'data_sources', ['tenant_id'], unique=False)
    op.create_table('segments',
    sa.Column('reconciliation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_reconciliation_id'), 'segments', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_segments_tenant_id'), 'segments', ['tenant_id'], unique=False)
    op.create_table('tenant_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'viewer'"), nullable=False),
    sa.Column('invited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'clerk_user_id', name='uq_tenant_member')
    )
    op.create_index(op.f('ix_tenant_members_tenant_id'), 'tenant_members', ['tenant_id'], unique=False)
    op.create_table('unions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unions_tenant_id'), 'unions', ['tenant_id'], unique=False)
    op.create_table('calculated_columns',
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculated_columns_data_source_id'), 'calculated_columns', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_calculated_columns_tenant_id'), 'calculated_columns', ['tenant_id'], unique=False)
    op.create_table('data_source_columns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sample_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'name', name='uq_data_source_column_name')
    )
    op.create_index(op.f('ix_data_source_columns_data_source_id'), 'data_source_columns', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_data_source_columns_tenant_id'), 'data_source_columns', ['tenant_id'], unique=False)
    op.create_table('data_source_rows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_rows_data_source_id'), 'data_source_rows', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_data_source_rows_tenant_id'), 'data_source_rows', ['tenant_id'], unique=False)
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('group_by_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aggregations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_source_id'), 'groups', ['source_id'], unique=False)
    op.create_index(op.f('ix_groups_tenant_id'), 'groups', ['tenant_id'], unique=False)
    op.create_table('joins',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('left_source_id', sa.UUID(), nullable=False),
    sa.Column('right_source_id', sa.UUID(), nullable=False),
    sa.Column('join_type', sa.String(length=20), server_default=sa.text("'inner'"), nullable=False),
    sa.Column('join_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['left_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['right_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joins_left_source_id'), 'joins', ['left_source_id'], unique=False)
    op.create_index(op.f('ix_joins_right_source_id'), 'joins', ['right_source_id'], unique=False)
    op.create_index(op.f('ix_joins_tenant_id'), 'joins', ['tenant_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recon_type', sa.String(length=50), nullable=True),
    sa.Column('left_source_id', sa.UUID(), nullable=False),
    sa.Column('right_source_id', sa.UUID(), nullable=False),
    sa.Column('left_source_label', sa.String(length=100), server_default=sa.text("'Source A'"), nullable=False),
    sa.Column('right_source_label', sa.String(length=100), server_default=sa.text("'Source B'"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('tolerance_amount', sa.Numeric(precision=19, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('tolerance_percent', sa.Numeric(precision=8, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['left_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['right_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_left_source_id'), 'reconciliations', ['left_source_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_right_source_id'), 'reconciliations', ['right_source_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_tenant_id'), 'reconciliations', ['tenant_id'], unique=False)
    op.create_table('segment_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_side', sa.String(length=10), nullable=False, comment='left | right | both'),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logic_group', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_rules_segment_id'), 'segment_rules', ['segment_id'], unique=False)
    op.create_index(op.f('ix_segment_rules_tenant_id'), 'segment_rules', ['tenant_id'], unique=False)
    op.create_table('union_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('union_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('union_id', 'data_source_id', name='uq_union_member')
    )
    op.create_index(op.f('ix_union_members_data_source_id'), 'union_members', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_union_members_union_id'), 'union_members', ['union_id'], unique=False)
    op.create_table('compensations',
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('compensation_type', sa.String(length=50), nullable=True),
    sa.Column('threshold_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('auto_apply', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensations_reconciliation_id'), 'compensations', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_compensations_tenant_id'), 'compensations', ['tenant_id'], unique=False)
    op.create_table('journal_templates',
    sa.Column('reconciliation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_templates_reconciliation_id'), 'journal_templates', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_journal_templates_tenant_id'), 'journal_templates', ['tenant_id'], unique=False)
    op.create_table('recon_rules',
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_rules_reconciliation_id'), 'recon_rules', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_recon_rules_tenant_id'), 'recon_rules', ['tenant_id'], unique=False)
    op.create_table('recon_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('left_row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('right_row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('matched_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unmatched_left', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unmatched_right', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('exception_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('match_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_runs_reconciliation_id'), 'recon_runs', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_recon_runs_tenant_id'), 'recon_runs', ['tenant_id'], unique=False)
    op.create_table('schedules',
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notify_on_complete', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_on_failure', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notification_emails', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_reconciliation_id'), 'schedules', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    op.create_table('sweeps',
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sweep_type', sa.String(length=50), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sweeps_reconciliation_id'), 'sweeps', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_sweeps_tenant_id'), 'sweeps', ['tenant_id'], unique=False)
    op.create_table('accounting_entries',
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recon_runs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['journal_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_entries_run_id'), 'accounting_entries', ['run_id'], unique=False)
    op.create_index(op.f('ix_accounting_entries_template_id'), 'accounting_entries', ['template_id'], unique=False)
    op.create_index(op.f('ix_accounting_entries_tenant_id'), 'accounting_entries', ['tenant_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_source_row_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('exception_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_row_id'], ['data_source_rows.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recon_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_data_source_row_id'), 'exceptions', ['data_source_row_id'], unique=False)
    op.create_index(op.f('ix_exceptions_run_id'), 'exceptions', ['run_id'], unique=False)
    op.create_index(op.f('ix_exceptions_tenant_id'), 'exceptions', ['tenant_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('export_scope', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recon_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_run_id'), 'export_jobs', ['run_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_tenant_id'), 'export_jobs', ['tenant_id'], unique=False)
    op.create_table('match_pairs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('left_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('right_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('difference', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('match_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['recon_rules.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recon_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_pairs_rule_id'), 'match_pairs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_match_pairs_run_id'), 'match_pairs', ['run_id'], unique=False)
    op.create_index(op.f('ix_match_pairs_tenant_id'), 'match_pairs', ['tenant_id'], unique=False)
    op.create_table('recon_rule_conditions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('left_column', sa.String(length=255), nullable=False),
    sa.Column('right_column', sa.String(length=255), nullable=False),
    sa.Column('comparison', sa.String(length=50), nullable=False),
    sa.Column('tolerance_value', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('fuzzy_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_key', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['recon_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_rule_conditions_rule_id'), 'recon_rule_conditions', ['rule_id'], unique=False)
    op.create_table('accounting_entry_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=19, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=19, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('match_pair_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['accounting_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_pair_id'], ['match_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_entry_lines_entry_id'), 'accounting_entry_lines', ['entry_id'], unique=False)
    op.create_index(op.f('ix_accounting_entry_lines_match_pair_id'), 'accounting_entry_lines', ['match_pair_id'], unique=False)
    op.create_table('match_pair_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('match_pair_id', sa.UUID(), nullable=False),
    sa.Column('data_source_row_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['data_source_row_id'], ['data_source_rows.id'], ),
    sa.ForeignKeyConstraint(['match_pair_id'], ['match_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_pair_id', 'data_source_row_id', name='uq_match_pair_item')
    )
    op.create_index(op.f('ix_match_pair_items_data_source_row_id'), 'match_pair_items', ['data_source_row_id'], unique=False)
    op.create_index(op.f('ix_match_pair_items_match_pair_id'), 'match_pair_items', ['match_pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_pair_items_match_pair_id'), table_name='match_pair_items')
    op.drop_index(op.f('ix_match_pair_items_data_source_row_id'), table_name='match_pair_items')
    op.drop_table('match_pair_items')
    op.drop_index(op.f('ix_accounting_entry_lines_match_pair_id'), table_name='accounting_entry_lines')
    op.drop_index(op.f('ix_accounting_entry_lines_entry_id'), table_name='accounting_entry_lines')
    op.drop_table('accounting_entry_lines')
    op.drop_index(op.f('ix_recon_rule_conditions_rule_id'), table_name='recon_rule_conditions')
    op.drop_table('recon_rule_conditions')
    op.drop_index(op.f('ix_match_pairs_tenant_id'), table_name='match_pairs')
    op.drop_index(op.f('ix_match_pairs_run_id'), table_name='match_pairs')
    op.drop_index(op.f('ix_match_pairs_rule_id'), table_name='match_pairs')
    op.drop_table('match_pairs')
    op.drop_index(op.f('ix_export_jobs_tenant_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_run_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_exceptions_tenant_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_run_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_data_source_row_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_accounting_entries_tenant_id'), table_name='accounting_entries')
    op.drop_index(op.f('ix_accounting_entries_template_id'), table_name='accounting_entries')
    op.drop_index(op.f('ix_accounting_entries_run_id'), table_name='accounting_entries')
    op.drop_table('accounting_entries')
    op.drop_index(op.f('ix_sweeps_tenant_id'), table_name='sweeps')
    op.drop_index(op.f('ix_sweeps_reconciliation_id'), table_name='sweeps')
    op.drop_table('sweeps')
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_reconciliation_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_recon_runs_tenant_id'), table_name='recon_runs')
    op.drop_index(op.f('ix_recon_runs_reconciliation_id'), table_name='recon_runs')
    op.drop_table('recon_runs')
    op.drop_index(op.f('ix_recon_rules_tenant_id'), table_name='recon_rules')
    op.drop_index(op.f('ix_recon_rules_reconciliation_id'), table_name='recon_rules')
    op.drop_table('recon_rules')
    op.drop_index(op.f('ix_journal_templates_tenant_id'), table_name='journal_templates')
    op.drop_index(op.f('ix_journal_templates_reconciliation_id'), table_name='journal_templates')
    op.drop_table('journal_templates')
    op.drop_index(op.f('ix_compensations_tenant_id'), table_name='compensations')
    op.drop_index(op.f('ix_compensations_reconciliation_id'), table_name='compensations')
    op.drop_table('compensations')
    op.drop_index(op.f('ix_union_members_union_id'), table_name='union_members')
    op.drop_index(op.f('ix_union_members_data_source_id'), table_name='union_members')
    op.drop_table('union_members')
    op.drop_index(op.f('ix_segment_rules_tenant_id'), table_name='segment_rules')
    op.drop_index(op.f('ix_segment_rules_segment_id'), table_name='segment_rules')
    op.drop_table('segment_rules')
    op.drop_index(op.f('ix_reconciliations_tenant_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_right_source_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_left_source_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_joins_tenant_id'), table_name='joins')
    op.drop_index(op.f('ix_joins_right_source_id'), table_name='joins')
    op.drop_index(op.f('ix_joins_left_source_id'), table_name='joins')
    op.drop_table('joins')
    op.drop_index(op.f('ix_groups_tenant_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_source_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_data_source_rows_tenant_id'), table_name='data_source_rows')
    op.drop_index(op.f('ix_data_source_rows_data_source_id'), table_name='data_source_rows')
    op.drop_table('data_source_rows')
    op.drop_index(op.f('ix_data_source_columns_tenant_id'), table_name='data_source_columns')
    op.drop_index(op.f('ix_data_source_columns_data_source_id'), table_name='data_source_columns')
    op.drop_table('data_source_columns')
    op.drop_index(op.f('ix_calculated_columns_tenant_id'), table_name='calculated_columns')
    op.drop_index(op.f('ix_calculated_columns_data_source_id'), table_name='calculated_columns')
    op.drop_table('calculated_columns')
    op.drop_index(op.f('ix_unions_tenant_id'), table_name='unions')
    op.drop_table('unions')
    op.drop_index(op.f('ix_tenant_members_tenant_id'), table_name='tenant_members')
    op.drop_table('tenant_members')
    op.drop_index(op.f('ix_segments_tenant_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_reconciliation_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_data_sources_tenant_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_consolidations_tenant_id'), table_name='consolidations')
    op.drop_table('consolidations')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
